# Tags can be applied to plays, blocks, roles, tasks, imports

- hosts: localhost
  gather_facts: false
  vars:
    - name: "Joe"

  tasks:
    - name: Create file based on template
      template:
        src: "hello_world.j2"
        dest: "/tmp/hello_world.txt"

    - name: Read file content
      set_fact:
        content: "{{ lookup('file', '/tmp/hello_world.txt') }}"

    - name: Print content
      debug:
        msg: "Content: [{{ content }}]"
