- hosts: localhost
  gather_facts: false

  # roles run after pre-task
  roles:
    - common

  pre_tasks:
    - set_fact:
        events: ["pretask1"]

  tasks:
    - set_fact:
        events: "{{ events + ['task1'] }}"

  # handlers run between tasks and post_tasks

  post_tasks:
    - set_fact:
        events: "{{ events + ['posttask1'] }}"
    - name: Verification
      assert:
        that:
          - events == ["pretask1", "InitRole", "Jack Biden", "param1", "roletask1", "role lib task", "task1", "Handler1", "posttask1"]
        

