- hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml

  pre_tasks:
    - debug:
        msg: "TODO pre-task"

  roles:
    - findhosts
    - common
    - webservers

  tasks:
#    - name: Read EC2 info
#      ec2_instance_info:
#        aws_access_key: "{{ aws_access_key }}"
#        aws_secret_key: "{{ aws_secret_key }}"
#        ec2_url: "{{ aws_ec2_url }}"
#        region: "{{ aws_region }}"
#        validate_certs: false
#      register: ec2_metadata
#
#    - name: print ec2 facts of TEST TEST
#      debug:
#        msg: "{{ ec2_metadata.instances | list  }}"
#
#    - name: Add new instance to host group
#      add_host:
#        hostname: "{{ item.public_dns_name }}"
#        groupname: launched
#      loop: "{{ ec2_metadata.instances | list }}"

#    - name: Provision instance
#      ec2:
#        aws_access_key: "{{ aws_access_key }}"
#        aws_secret_key: "{{ aws_secret_key }}"
#        ec2_url: "{{ aws_ec2_url }}"
#        validate_certs: false
#        instance_type: t2.micro
#        image: "ami-0d57c0143330e1fa7"
#        wait: yes
#        count: 1
#        region: "{{ aws_region }}"

  post_tasks:
    - debug:
        msg: "TODO post-task"

- hosts: launched_ec2s
  roles:
    - webservers
