- name: Verify host vars are set properly
  hosts: all

  tasks:
    -
    - name: Ensure the vars are set correctly on webserver-instance-1
      assert:
        that:
          - db is undefined
          - disk == "32GB"
          - load_balancer == "nginx"
      when: inventory_hostname == "webserver-instance-1"

    - name: Ensure the vars are set correctly on webserver-instance-2
      assert:
        that:
          - db is undefined
          - disk == "32GB"
          - load_balancer == "nginx"
      when: inventory_hostname == "webserver-instance-2"

    - name: Ensure the vars are set correctly on db-instance-1
      assert:
        that:
          - load_balancer is undefined
          - replica is undefined
          - disk == "1TB"
          - db == "oracle"
      when: inventory_hostname == "db-instance-1"

    - name: Ensure the vars are set correctly on db-instance-2
      assert:
        that:
          - load_balancer is undefined
          - disk == "1TB"
          - db == "oracle"
          - replica == True # coming from host_vars
      when: inventory_hostname == "db-instance-2"
